#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : freeglut
Version  : 3.0.0
Release  : 1
URL      : http://downloads.sourceforge.net/project/freeglut/freeglut/3.0.0/freeglut-3.0.0.tar.gz
Source0  : http://downloads.sourceforge.net/project/freeglut/freeglut/3.0.0/freeglut-3.0.0.tar.gz
Summary  : A freely licensed and improved alternative to the GLUT library
Group    : Development/Tools
License  : MIT
Requires: freeglut-lib
BuildRequires : cmake
BuildRequires : glu-dev
BuildRequires : libXi-dev

%description
BRIEF OVERVIEW
==============
This is the freeglut package.
Freeglut, the Free OpenGL Utility Toolkit, is meant to be a free alternative to
Mark Kilgard's GLUT library. Freeglut is free software, distributed under an
MIT/X11 style license. You are free to use, modify, and redistribute FreeGLUT
with or without modifications (see COPYING for details).

%package dev
Summary: dev components for the freeglut package.
Group: Development
Requires: freeglut-lib
Provides: freeglut-devel

%description dev
dev components for the freeglut package.


%package lib
Summary: lib components for the freeglut package.
Group: Libraries

%description lib
lib components for the freeglut package.


%prep
%setup -q -n freeglut-3.0.0

%build
mkdir clr-build
pushd clr-build
cmake .. -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS:BOOL=ON -DLIB_INSTALL_DIR:PATH=%{_libdir}
make V=1  %{?_smp_mflags}
popd

%install
rm -rf %{buildroot}
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/GL/freeglut.h
/usr/include/GL/freeglut_ext.h
/usr/include/GL/freeglut_std.h
/usr/include/GL/glut.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
